### PR TITLE
Feature/remove pronto

### PR DESCRIPTION
**Pull request by bowsiak**
Remove unused pronto and pronto-rubocop gems. pronto-rubocop had rubocop 0.36.0 in dependencies, so we couldn't upgrade it to 0.37.0. That was the cause of CodeClimate fails.

### CODE REVIEW

**Comment by bowsiak** [comment]
@adamzima @mknapik could you review?

**Comment by bowsiak** [comment]
nvm, it's in still in progress ;]

**Comment by lauratpa** [comment]
they bumped up `rubocop-rspec` :) https://github.com/nevir/rubocop-rspec/commit/9aa33ee7014e8d6d580b12fe2651b32ccdaa7a92

**Comment by lauratpa** [comment]
@adamzima @mknapik ping! I think this PR is good to go now!

**Comment by adamzima** [comment]
looks good to me

**Pull request merged**
